// This file is the entrypoint of your package. Generated by Typstify.
#show outline.entry.where(
  level: 1
): set block(above: 1.2em)
#outline()

#include "rust_tour/linux.typ"

#include "rust_tour/windows.typ"

#include "rust_tour/code_editor.typ"

#include "rust_tour/projects_creation.typ"

#include "rust_tour/rust_error_handler.typ"

#include "rust_lang/1_rust_data_types.typ"

#include "rust_lang/2_copy_and_non_copy.typ"

#include "rust_lang/3_ownership_and_borrow.typ"

#include "rust_lang/4_functions.typ"

#include "rust_lang/5_structs.typ"

#include "rust_cheatSheet/cheatsheet.typ"

#include "rust_cheatSheet/basictypes_and_var.typ"

#include "rust_cheatSheet/control_flow.typ"

#include "rust_cheatSheet/reference_ownership_borrowing.typ"

#include "rust_cheatSheet/pattern_matching.typ"

#include "rust_cheatSheet/iterators_error_handling.typ"
#include "rust_cheatSheet/combinators_multiple errortypes_iterating_over_errors.typ"
#include "rust_cheatSheet/generics_traits_lifetime.typ"
#include "rust_cheatSheet/lifetimes_functions_pointers_closures.typ"
#include "rust_cheatSheet/pointers_smart_package_crates&modules.typ"

#include "rust_cheatSheet/packages_modules_crates_continue.typ"