// This file is the entrypoint of your package. Generated by Typstify.
#show outline.entry.where(
  level: 1
): set block(above: 1.2em)
#outline()

#include "rust_tour/linux.typ"
#include "rust_tour/windows.typ"
#include "rust_tour/code_editor.typ"
#include "rust_tour/projects_creation.typ"
== A Friend in Need is a Friend Indeed

= Rust Data Types
== Scalar Types
== Compound Types
== Collection Types (from std::collections)
== Never Type

= Rust Functions
== Introduction
== Defining Functions
== Parameters and Return Types
== Statements vs. Expressions
== Example
== Function Documentation

= Rust Structs
== What is a Struct?
== Creating Instances
== Tuple Structs
== Unit-Like Structs
== Implementing Methods

= Rust Ownership & Borrowing Rules
== Introduction
== Ownership Basics
=== Example
== Borrowing and References
=== Example
== Borrowing Rules
== Slices - Borrowing Parts of Data
